# Set language to NodeJS
language: node_js

# Cache node modules
cache: node_modules

# Set NodeJS to v5
node_js:
  - "5"

# Prepare files for JSHint
before_script:
  - FILES=$(find . -name \*.js ! -path './node_modules/*' -print)

script:
  # Run jshint to check files
  - jshint $FILES

notifications:
  # Send notifications to Slack
  slack:
    secure: ACROBONkDTENtkp+jB29mmUso/0HO6mKkE/0kKzYVZyfd0sSOpqrftL2PbZ9VPuxhly2xX5xOOPTpSjFrNplH1UFru00wm4RCUKYw3PpaGAmzWP6wOdfxVSKHV0Ngn8dpbUihUbvE7aiJ7w+YOjNaM9Nbbta1hubuvdzSaKTLpdy8bmOcNxqR7wsMTdQ5nkLH3e/oYhfbmt6ytBbk6d5Iw44ySKo94WVX85uBDoLr/VJBL6OvdRfD/3aecUo19+C9nuVq5pGQDGRpcvM4/m2DEftsYBiEl/d3BcCTnVnReeXwoN+YcDpO2nNQu3A3i7P5c3aP+02c4V+EZ0XquSlMjcHPl93xVp0VAdoCtwFs271GicQt1z3+5drUYXFhGfJgBGXuv8nvKM3mL+6K8tiyVdv/ckF/oy35jD9yIWbWb0mtna3vXAAX/cnhs2OzKWnHiEUtSvQKlKz0JS36mc5zVF0IMmOfCanrP9JXE1V4+Yc9WJ8RTzM7/ccSMl/HtcufQPwO6ywhD8X1AlgOynzin0YxB62Rk0aBPDBYd5ZPXp9YHVJSIQS2KEabm9xTbcndzkL0sTYG9b+6QPKO4KtPxZU4qC1ugaEkfGT399/MhLf1p/U9nvPsIPNAEqVdRHdQcDgO+qOn5a0/ciGC3RiP9gAxABtkTFSxxhy/FICWr4=
